server:
  port: 3306
spring:
  profiles:
    active: prod
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://119.28.25.204:3306/yftpay2?autoReconnect=true
#    username: eric123
#    password: eric123
    url: jdbc:mysql://localhost:3306/side_project?autoReconnect=true&useSSL=false
    username: kiz7386
    password: 123$zxcV
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true